### ISSUE TITLE
Unable to install plugin -- Error: pod: Command failed with exit code 1

### ISSUE THREAD

**Issue by bmonson** [AppliedRecognition/Ver-ID-Person-Cordova-Plugin#9]
After cloning the plugin repo to a local directory, I ran 

`cordova plugin add <path to the plugin>`

but I am getting the error below:

```
Failed to install 'com-appliedrec-plugins-verid': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (<path to cordova app>/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

output from `cordova info`:

```
Node version: v11.7.0

Cordova version: 8.1.1

Config.xml file: 

<?xml version='1.0' encoding='utf-8'?>
<widget id="com.cleansmarts.app" version="1.7.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name> APP </name>
    <description>
        APP
    </description>
    <content src="index.html" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="android-targetSdkVersion" value="26" />
    <preference name="android-build-tool" value="gradle" />
    <preference name="camera-uses-geolocation" value="true" />
    <feature name="Camera">
        <param name="ios-package" value="CDVCamera" />
    </feature>
    <feature name="Capture">
        <param name="ios-package" value="CDVCapture" />
    </feature>
    <feature name="TouchID">
        <param name="ios-package" value="TouchID" />
    </feature>
    <edit-config file="*-Info.plist" mode="merge" target="NSLocationWhenInUseUsageDescription">
        <string>This app needs location access in order to provide your employer with your location when you check in and out of your job or at a barcode waypoint.</string>
    </edit-config>
    <edit-config file="*-Info.plist" mode="merge" target="NSCameraUsageDescription">
        <string>This app needs camera access to take pictures that you would like to attach to messages, issues, or other communications, or to scan barcodes tied to sublocations.</string>
    </edit-config>
    <edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryUsageDescription">
        <string>This app needs photo library access to get pictures or videos that you would like to attach to messages, issues, or other communications.</string>
    </edit-config>
    <edit-config file="*-Info.plist" mode="merge" target="NSLocationWhenInUseUsageDescription">
        <string>This app needs location access in order to provide your employer with your location when you check in and out of your job or at a barcode waypoint.</string>
    </edit-config>
    <edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryAddUsageDescription">
        <string>This app needs photo library access to save pictures that you would like to attach to messages, issues, or other communications.</string>
    </edit-config>
    <edit-config file="*-Info.plist" mode="merge" target="com.appliedrec.verid.apiSecret">
        <string>api_secret_was_here</string>
    </edit-config>
    <platform name="android">
        <hook src="scripts/patch-android-studio-check.js" type="before_plugin_install" />
        <hook src="scripts/patch-android-studio-check.js" type="before_plugin_install" />
        <hook src="scripts/patch-android-studio-check.js" type="before_plugin_add" />
        <hook src="scripts/patch-android-studio-check.js" type="before_build" />
        <hook src="scripts/patch-android-studio-check.js" type="before_run" />
        <hook src="scripts/patch-android-studio-check.js" type="before_plugin_rm" />
        <hook src="scripts/move-fingerprint-file.js" type="before_build" />
        <resource-file src="google-services.json" target="app/google-services.json" />
        ...
        <preference name="ShowSplashScreenSpinner" value="false" />
        <preference name="AutoHideSplashScreen" value="false" />
        <preference name="FadeSplashScreen" value="true" />
        <preference name="FadeSplashScreenDuration" value="500" />
        <preference name="com.appliedrec.verid.apiSecret" value="secret_here" />
    </platform>
    <platform name="ios">
        <preference name="deployment-target" value="11.0" />
        <resource-file src="GoogleService-Info.plist" />
        ...
        <preference name="ShowSplashScreenSpinner" value="false" />
        <preference name="AutoHideSplashScreen" value="false" />
        <preference name="FadeSplashScreen" value="true" />
        <preference name="FadeSplashScreenDuration" value="500" />
        <preference name="StatusBarStyle" value="blacktranslucent" />
        <preference name="StatusBarBackgroundColor" value="#333" />
    </platform>
    <access origin="https://cleansmarts.com" subdomains="true" />
    <access launch-external="yes" origin="geo:*" />
    <access launch-external="yes" origin="tel:*" />
    <access launch-external="yes" origin="maps:*" />
    <access origin="*.google.com" />
    <access origin="*.googleapis.com" />
    <access origin="*.gstatic.com" />
    <allow-intent href="gap:" />
    <allow-intent href="data:" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <allow-intent href="maps:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <plugin name="cordova-plugin-camera" spec="^4.0.3" />
    <plugin name="cordova-plugin-device" spec="~2.0.2" />
    <plugin name="cordova-plugin-dialogs" spec="^2.0.1" />
    <plugin name="cordova-plugin-file-transfer" spec="~1.7.1" />
    <plugin name="cordova-plugin-geolocation" spec="^4.0.1" />
    <plugin name="cordova-plugin-media-capture" spec="~3.0.2" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-plugin-statusbar" spec="~2.4.2" />
    <plugin name="cordova-plugin-whitelist" spec="~1.3.3" />
    <plugin name="cordova-plugin-ios-camera-permissions" spec="~1.2.0">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="This app needs camera access" />
        <variable name="MICROPHONE_USAGE_DESCRIPTION" value="This app needs microphone access" />
        <variable name="PHOTOLIBRARY_ADD_USAGE_DESCRIPTION" value="This app needs write-access to photo library" />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="This app needs read/write-access photo library access" />
    </plugin>
    <plugin name="phonegap-plugin-barcodescanner" spec="~8.0.0" />
    <plugin name="cordova-plugin-inappbrowser" spec="~3.0.0" />
    <plugin name="cordova-plugin-keychain-touch-id" spec="^3.2.1" />
    <plugin name="cordova-sqlite-storage" spec="^2.4.0" />
    <plugin name="cordova-android-play-services-gradle-release" spec="^1.4.3" />
    <plugin name="cordova-android-firebase-gradle-release" spec="~1.0.2" />
    <plugin name="phonegap-plugin-push" spec="^2.2.3">
        <variable name="FCM_VERSION" value="11.6.2" />
    </plugin>
    <plugin name="cordova-android-support-gradle-release" spec="^1.4.5">
        <variable name="ANDROID_SUPPORT_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-background-geolocation" spec="https://github.com/transistorsoft/cordova-background-geolocation.git">
    </plugin>
    <plugin name="com-appliedrec-plugins-verid" spec="/Users/cleansmarts/Documents/app/cloned_plugins/Ver-ID-Person-Cordova-Plugin" />
    <engine name="browser" spec="^5.0.3" />
    <engine name="ios" spec="^4.5.5" />
</widget>


Plugins: 

com-appliedrec-plugins-verid,cordova-android-firebase-gradle-release,cordova-android-play-services-gradle-release,cordova-android-support-gradle-release,cordova-background-geolocation,cordova-plugin-background-fetch,cordova-plugin-camera,cordova-plugin-cocoalumberjack,cordova-plugin-device,cordova-plugin-dialogs,cordova-plugin-file,cordova-plugin-file-transfer,cordova-plugin-geolocation,cordova-plugin-inappbrowser,cordova-plugin-ios-camera-permissions,cordova-plugin-keychain-touch-id,cordova-plugin-media-capture,cordova-plugin-network-information,cordova-plugin-statusbar,cordova-plugin-whitelist,cordova-sqlite-storage,cordova-support-google-services,phonegap-plugin-barcodescanner,phonegap-plugin-multidex,phonegap-plugin-push

iOS platform:

Xcode 10.1
Build version 10B61

```

**Comment by bmonson** [comment]
Maybe making some headway...when I attempt to remove the ios platform, I am now consistently getting npm errors:

`npm ERR! notarget No matching version found for brace-expansion@undefined1.1.11`

The weird thing is that the package name is different every time I remove and add the ios platform. But they all are printing `undefined` between the package name and the version number. Another example:

```
npm ERR! notarget No matching version found for assertion-error@undefined1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'ver-id-cordova-plugin'
```

**Comment by jakubdolejs** [comment]
Hello @bmonson, thank you for reporting the errors. I believe the error is thrown after the plugin is installed, despite the message making it sound like the installation failed.
Can you try adding the [podfilesetup.js](https://github.com/AppliedRecognition/Ver-ID-Person-Cordova-Plugin/blob/master/hooks/podfilesetup.js) hook into your project's config file with the type `before_build` and building the project after the supposedly failed plugin installation?

**Comment by jakubdolejs** [comment]
Here is an example with the above hook added. I listed the plugins on the first line just to show that Ver-ID wasn't installed.
```jakub@iMac~/Documents/AppliedRecognition/projects/CordovaTest3$ cordova plugin ls
cordova-plugin-whitelist 1.3.3 "Whitelist"
jakub@iMac~/Documents/AppliedRecognition/projects/CordovaTest3$ cordova plugin add ../Ver-ID-Cordova/
Installing "com-appliedrec-plugins-verid" for ios
Failed to install 'com-appliedrec-plugins-verid': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/jakub/Documents/AppliedRecognition/projects/CordovaTest3/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
pod: Command failed with exit code 1
jakub@iMac~/Documents/AppliedRecognition/projects/CordovaTest3$ cordova build
Running iOS setup for Ver-ID plugin
Wrote to /Users/jakub/Documents/AppliedRecognition/projects/CordovaTest3/platforms/ios/Podfile:
# DO NOT MODIFY -- auto-generated by Apache Cordova
platform :ios, '11.0'
target 'HelloCordova' do
	project 'HelloCordova.xcodeproj'
	pod 'Ver-ID', '~> 3.5'
end

Analyzing dependencies

Downloading dependencies
Installing Ver-ID (3.5.3)
Generating Pods project
Integrating client project
Sending stats

Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.


[!] The `HelloCordova [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-HelloCordova/Pods-HelloCordova.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `HelloCordova [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-HelloCordova/Pods-HelloCordova.release.xcconfig'. This can lead to problems with the CocoaPods installation

    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

Building for iPhone X Simulator
Building project: /Users/jakub/Documents/AppliedRecognition/projects/CordovaTest3/platforms/ios/HelloCordova.xcworkspace
	Configuration: Debug
	Platform: emulator
Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/jakub/Documents/AppliedRecognition/projects/CordovaTest3/platforms/ios/build/emulator
    SDKROOT = iphonesimulator12.1
    SHARED_PRECOMPS_DIR = /Users/jakub/Documents/AppliedRecognition/projects/CordovaTest3/platforms/ios/build/sharedpch

Build settings from configuration file '/Users/jakub/Documents/AppliedRecognition/projects/CordovaTest3/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Ver-ID"
    GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
    HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/Ver-ID"
    LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
    OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/Ver-ID"
    OTHER_LDFLAGS = $(inherited) -ObjC -framework "VerID"
    PODS_BUILD_DIR = ${BUILD_DIR}
    PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
    PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
    PODS_ROOT = ${SRCROOT}/Pods
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

jakub@iMac~/Documents/AppliedRecognition/projects/CordovaTest3$ cordova plugin ls
com-appliedrec-plugins-verid 4.2.0 "Ver-ID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
jakub@iMac~/Documents/AppliedRecognition/projects/CordovaTest3$```

**Comment by bmonson** [comment]
Hi @jakubdolejs, I was able to complete a build with that hook, thanks! I've got a new problem now, but I'll close this issue and open a new one since it relates to Javascript.
